development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  # url: <%= ENV["REDISCLOUD_URL"] %>
  url: redis://127.0.0.1:6379/1
  # channel_prefix: readyplayercode_production
